# Generated by Django 5.1.2 on 2024-10-12 19:38

import uuid

from django.db import migrations, models

import supertrack.helpers.filer


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=supertrack.helpers.filer.ticket_image_upload_path,
                    ),
                ),
                (
                    "total",
                    models.FloatField(default=0.0, verbose_name="Total"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
