# Generated by Django 5.1.2 on 2024-10-12 20:08

import supertrack.helpers.filer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='image',
            field=models.FileField(upload_to=supertrack.helpers.filer.ticket_image_upload_path),
        ),
    ]
