# Generated by Django 5.1.2 on 2024-10-15 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticketproductmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketproductmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ticketproductmodel',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketproductmodel',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='ticketproductmodel',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='TicketProductRelationshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('unit_price', models.FloatField(default=0.0, verbose_name='Price')),
                ('total_price', models.FloatField(default=0.0, verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.ticketproductmodel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.ticketmodel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
