version: "3"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=supertrack
      - POSTGRES_NAME=supertrack
      - POSTGRES_USER=supertrack
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks:
      mynet:
        ipv4_address: 173.25.0.2

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 173.25.0.0/16
