# Generated by Django 5.1.2 on 2024-10-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_mercadonashoppinglistproduct_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadonashoppinglistproduct',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shopping_list.mercadonashoppinglist'),
        ),
    ]
