# Generated by Django 5.1.2 on 2024-10-31 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercadonacategorymodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mercadonaparentcategorymodel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mercadonaparentcategorymodel',
            name='parent_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scrappy.internalcategory'),
            preserve_default=False,
        ),
    ]
