# Generated by Django 5.1.2 on 2024-10-14 11:36

import django.db.models.deletion
import supertrack.helpers.filer
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadonaProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('internal_id', models.IntegerField(verbose_name='Internal ID')),
                ('image', models.ImageField(upload_to=supertrack.helpers.filer.mercadona_category_product_image_upload_path, verbose_name='Image')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrappy.mercadonacategorymodel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
