# Generated by Django 5.1.2 on 2024-10-31 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0002_alter_mercadonacategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadonacategorymodel',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrappy.internalsubcategory'),
        ),
    ]
