# Generated by Django 5.1.2 on 2024-10-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0002_mercadonaproductcategorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadonaproductmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrappy.mercadonaproductcategorymodel'),
        ),
    ]
