# Generated by Django 5.1.2 on 2024-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0003_alter_mercadonaproductmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadonacategorymodel',
            name='internal_id',
            field=models.CharField(max_length=100, verbose_name='Internal ID'),
        ),
        migrations.AlterField(
            model_name='mercadonaparentcategorymodel',
            name='internal_id',
            field=models.CharField(max_length=100, verbose_name='Internal ID'),
        ),
        migrations.AlterField(
            model_name='mercadonaproductcategorymodel',
            name='internal_id',
            field=models.CharField(max_length=100, verbose_name='Internal ID'),
        ),
        migrations.AlterField(
            model_name='mercadonaproductmodel',
            name='internal_id',
            field=models.CharField(max_length=100, verbose_name='Internal ID'),
        ),
    ]
