# Generated by Django 5.1.2 on 2024-10-31 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0003_alter_mercadonacategorymodel_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercadonaparentcategorymodel',
            old_name='parent_category',
            new_name='parent_internal_category',
        ),
        migrations.AddField(
            model_name='mercadonacategorymodel',
            name='subcategory_internal_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scrappy.internalsubcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mercadonacategorymodel',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrappy.mercadonaparentcategorymodel'),
        ),
    ]
