# Generated by Django 5.1.2 on 2024-10-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0004_alter_mercadonacategorymodel_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadonaproductmodel',
            name='slug',
            field=models.SlugField(max_length=400, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='mercadonaproductmodel',
            name='total_price',
            field=models.FloatField(default=0.0, verbose_name='Total Price'),
        ),
    ]
