# Generated by Django 5.1.2 on 2024-10-28 17:52

import django.db.models.deletion
import supertrack.helpers.filer
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0005_alter_mercadonaproductmodel_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumParentCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('internal_id', models.CharField(max_length=100, verbose_name='Internal ID')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('internal_id', models.CharField(max_length=100, verbose_name='Internal ID')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrappy.consumparentcategorymodel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('internal_id', models.CharField(max_length=100, verbose_name='Internal ID')),
                ('image', models.ImageField(upload_to=supertrack.helpers.filer.consum_category_product_image_upload_path, verbose_name='Image')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrappy.consumcategorymodel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('internal_id', models.CharField(max_length=100, verbose_name='Internal ID')),
                ('unit_price', models.FloatField(default=0.0, verbose_name='Price')),
                ('total_price', models.FloatField(default=0.0, verbose_name='Total Price')),
                ('image', models.ImageField(upload_to=supertrack.helpers.filer.consum_product_image_upload_path, verbose_name='Image')),
                ('slug', models.SlugField(max_length=400, verbose_name='Slug')),
                ('is_new', models.BooleanField(default=False, verbose_name='Is new')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrappy.consumproductcategorymodel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
