# Generated by Django 5.1.2 on 2024-10-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0006_consumparentcategorymodel_consumcategorymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumproductcategorymodel',
            name='image',
        ),
    ]
