# Generated by Django 5.1.2 on 2024-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0007_remove_consumproductcategorymodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumproductmodel',
            old_name='total_price',
            new_name='offer_price',
        ),
        migrations.RemoveField(
            model_name='consumproductmodel',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='consumproductmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='consumproductmodel',
            name='offer_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumproductmodel',
            name='offer_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
