# Generated by Django 5.1.2 on 2024-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0008_rename_total_price_consumproductmodel_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumproductmodel',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image'),
        ),
    ]
