# Generated by Django 5.1.2 on 2024-10-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0010_alter_consumcategorymodel_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadonaproductcategorymodel',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mercadonaproductmodel',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image'),
        ),
    ]
