export const GET_MERCADONA_PRODUCTS = 'shopping_list/GET_MERCADONA_PRODUCTS';
export const GET_MERCADONA_PRODUCTS_SUCCESS = 'shopping_list/GET_MERCADONA_PRODUCTS_SUCCESS';
export const DISPLAY_SUPERMARKET_PRODUCTS = 'shopping_list/DISPLAY_SUPERMARKET_PRODUCTS';
export const DISPLAY_SUPERMARKET_PRODUCTS_SUCCESS = 'shopping_list/DISPLAY_SUPERMARKET_PRODUCTS_SUCCESS';
export const SUPERMARKET_PRODUCTS_SELECTED = 'shopping_list/SUPERMARKET_PRODUCTS_SELECTED';
